site_name: simply-static-post-process
site_description: Python Package to Create, Manipulate and Analyze Website Sitemaps
site_author: SERP Wings

site_url: https://simply-static.netlify.app

repo_url: https://github.com/serpwings/simply-static-post-process
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API: 
    - simply-static-netlify object: simply-static-netlify.md
    - Helper Functions: helper-functions.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list
  
theme: readthedocs

copyright: © Copyright 2023 SERP Wings